AWDProjectFinal/Controllers/OwnersController.cs
using AWDProjectFinal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace AWDProjectFinal.Controllers
{
    public class OwnersController : Controller
    {
        HttpClientHandler _clientHandler = new HttpClientHandler();
        string host = "https://localhost:7253/api/Owner";
        private readonly IWebHostEnvironment _hostEnvironment;


        public OwnersController(IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _clientHandler.ServerCertificateCustomValidationCallback =
                (sender, cert, chain, sslPolicyErrors) => { return true; };
        }
        // GET: OwnersController
        public async Task<IActionResult> Index()
        {
            var owner = await GetOwner();
            return View(owner);
        }
        [HttpGet]
        public async Task<IActionResult> Index(string search)
        {
            var owner = await GetOwner();
            if (!String.IsNullOrEmpty(search))
            {
                owner = owner.Where(sh => sh.Name!.Contains(search)).ToList();
            }

            return View(owner);
        }

        [HttpGet]
        public async Task<List<OwnerApartment>> GetOwner() {

            List<OwnerApartment> owners = new List<OwnerApartment>();

            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync(host))
                {
                    string strJson = await response.Content.ReadAsStringAsync();
                    owners = JsonConvert.DeserializeObject<List<OwnerApartment>>(strJson);
                }
            }

            return owners;
        }

        public async Task<ActionResult> Details(int id)
        {
            OwnerApartment ownerDt = new OwnerApartment();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:7253/api/Owner/id?id="+id))
                {
                    string strJson = await response.Content.ReadAsStringAsync();
                    ownerDt = JsonConvert.DeserializeObject<OwnerApartment>(strJson);
                }
               
            }
             return View(ownerDt);
        }

        // GET: OwnersController/Details/5
        /*public ActionResult Details(int id)
        {
            return View();
        }*/

        // GET: OwnersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OwnersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OwnerApartment ownerCreates)
        {
            
            try
            {

                OwnerApartment ownerC = new OwnerApartment();
                //string filename = UploadFile(ownerCreates);
                if (ownerCreates.ImageFile != null)
                {
                    string filePath = Path.Combine(_hostEnvironment.WebRootPath, "images", ownerCreates.Name);
                    System.IO.File.Delete(filePath);
                    ownerCreates.Image = UploadFile(ownerCreates);
                }

                using (var httpClient = new HttpClient(_clientHandler))
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(ownerCreates),Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync("https://localhost:7253/api/Owner", content))
                    {
                        
                        string strJson = await response.Content.ReadAsStringAsync();
                        ownerC = JsonConvert.DeserializeObject<OwnerApartment>(strJson);
                        Console.WriteLine(ownerC);
                        if (ModelState.IsValid)
                        {
                            return RedirectToAction(nameof(Index));
                           
                        }
                    }
                   
                }
                    return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OwnersController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            OwnerApartment owner = new OwnerApartment();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync(host+"/id?id=" + id))
                { 
                    string strJson = await response.Content.ReadAsStringAsync();
                    owner = JsonConvert.DeserializeObject<OwnerApartment>(strJson);
                }
            }
            return View(owner);
        }

        // POST: OwnersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,OwnerApartment owner)
        {
            OwnerApartment _owner = new OwnerApartment();

            if (owner.ImageFile!=null) {
                string filePath = Path.Combine(_hostEnvironment.WebRootPath, "images", owner.Name);
                System.IO.File.Delete(filePath);
                owner.Image = UploadFile(owner);
            }
            using (var httpClient = new HttpClient(_clientHandler))
            {
                StringContent content = 
                    new StringContent(JsonConvert.SerializeObject(owner),Encoding.UTF8,"application/json");

                using (var response = await httpClient.PutAsync(host + "/" + id,content))
                {
                    
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private string UploadFile(OwnerApartment p)
        {
            string fileName = "";
            if (p.ImageFile != null)
            {
                //upload to folder image in wwwroot
                string uploadDrive = Path.Combine(_hostEnvironment.WebRootPath, "images");
                fileName = Guid.NewGuid().ToString() + "-" + p.ImageFile.FileName;
                string filePath = Path.Combine(uploadDrive, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    p.ImageFile.CopyTo(fileStream);
                }
            }
            return fileName;
        }

        // GET: OwnersController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            string del = "";
            string host = "https://localhost:7253/api/Owner/";
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.DeleteAsync(host + id))
                {
                    del = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: OwnersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AWDProjectFinal/Views/Owners/Create.cshtml
@model AWDProjectFinal.Models.OwnerApartment

@{
    ViewData["Title"] = "Create";
}
<html>
    <head>
         <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SB Admin 2 - Dashboard</title>

        <!-- Custom fonts for this template-->
        <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    </head>
    <body>
        <h1 class="h1 mb-2 text-gray-900">Create</h1>

        <h4 class="h4 mb-2 text-gray-900">OwnerApartment</h4>
        <hr />
        <div class="row">
            <div class="card shadow col-md-6 center">
                <div style="margin:35px">
                    <form asp-action="Create" enctype="multipart/form-data" class="user">

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control form-control-user" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" class="form-control form-control-user" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>

                        <div>
                            <label asp-for="ImageFile" ></label>
                            <input asp-for="ImageFile" accept="images/*" class="center"/>
                        </div>
                        <br />
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary btn-user btn-block" />
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </body>
</html>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AWDProjectFinal/Views/Owners/Details.cshtml
@model AWDProjectFinal.Models.OwnerApartment

@{
    ViewData["Title"] = "Details";
}
<html>
    <head>
         <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SB Admin 2 - Dashboard</title>

        <!-- Custom fonts for this template-->
        <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    </head>
    <body>
        <h1 class="h1 mb-2 text-gray-900">Details</h1>

        <div>
            <h4 class="h4 mb-2 text-gray-900">OwnerApartment</h4>
            <hr />
            <div class="card shadow col-md-6 center">
                <div style="margin:35px">
                    <dl class="row">

                        <dt class = "col-sm-2">
                            @Html.DisplayNameFor(model => model.Id)
                        </dt>
                        <dd class = "col-sm-10">
                            @Html.DisplayFor(model => model.Id)
                        </dd>
                        <dt class = "col-sm-2">
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd class = "col-sm-10">
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt class = "col-sm-2">
                            @Html.DisplayNameFor(model => model.Phone)
                        </dt>
                        <dd class = "col-sm-10">
                            @Html.DisplayFor(model => model.Phone)
                        </dd>
                        <dt class = "col-sm-2">
                            @Html.DisplayNameFor(model => model.Image)
                        </dt>
                        <div class= "col-sm-10">
                                <img src="@("~/images/"+Model.Image)" width="100%" height="100%" asp-append-version=true/>
                             </div>
                     
                    </dl>
                </div>
            </div>
        </div>
        <div>
    
            <a asp-action="Index">Back to List</a>
        </div>
    </body>
</html>

AWDProjectFinal/Views/Owners/Edit.cshtml
@model AWDProjectFinal.Models.OwnerApartment

@{
    ViewData["Title"] = "Edit";
}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SB Admin 2 - Dashboard</title>

        <!-- Custom fonts for this template-->
        <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    </head>
    <body>
        <h1 class="h1 mb-2 text-gray-900">แก้ไขข้อมูลเจ้าของหอพัก</h1>
        <hr />
        
        <div class="row">
            <div class="card shadow col-md-6 center">
                <div style="margin:35px">
                <form asp-action="Edit" enctype="multipart/form-data" class="user" >
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="center">
                        <img src="@("~/images/"+Model.Image)" width="30%" height="30%" asp-append-version=true class="center"/>
                     </div>
                     <br />
                     <div>
                        <input asp-for="ImageFile" accept="images/*" class="center"/>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control form-control-user" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control form-control-user" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Image" class="control-label"></label>
                        <input asp-for="Image" class="form-control form-control-user" readonly/>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="แก้ไขข้อมูล" class="btn btn-primary btn-user btn-block " />
                    </div>
                </form>
                </div>
            </div>
        </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>
    </body>
</html>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AWDProjectFinal/Views/Owners/Index.cshtml
@model IEnumerable<AWDProjectFinal.Models.OwnerApartment>

@{
    ViewData["Title"] = "Index";
}
<html>
    <head>
         <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SB Admin 2 - Tables</title>

        <!-- Custom fonts for this template -->
        <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

        <!-- Custom styles for this page -->
        <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    </head>
    <body>
      <h1 class="h1 mb-2 text-gray-900">รายการเจ้าของหอพัก</h1>
        <br />
        
        <div class="card shadow mb-4">
            <div class="card-header py-3 bg-gradient-primary">
                <h6 class="m-0 font-weight-bold text-white">ตารางจัดการข้อมูลเจ้าของหอพัก</h6>
             </div>
             <br />
              <div class="col center">
                 <div class="row">
                     <div class="col-lg-9">
                         <div class="search-bar">        
                             <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" asp-controller="Owners" asp-action="Index" method="get">
                                 <input type="text" class="form-control bg-gray-200 border-0 small" name="search" placeholder="Search" title="Enter search keyword" width="200">
                                 <button type="submit" title="Search" class="btn btn-primary"><i class="fas fa-search fa-sm"></i></button>
                             </form>
                         </div>
                         
                    </div>
                    <div class="col-lg-3">
                        
                         <div style="width: 150px;">
                            <a asp-action="Create" class="btn btn-success btn-block" >Create New</a>
                        </div>
                    </div>
                 </div>
              </div>
            
            
            <div class="card-body">
              
                <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Phone)
                                </th>
                                <th  style="width: 50px;">
                                    @Html.DisplayNameFor(model => model.Image)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model) {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Phone)
                                    </td>
                                    <td  style="width: 50px;">
                                        @Html.DisplayFor(modelItem => item.Image)
                                    </td>
            
                                    <td>
                                    
                                        <div class="btn btn-info btn-circle btn-sm">
                                            <i class="fas fa-info-circle"></i>
                                        </div>
                                        @Html.ActionLink("Details", "Details", new {  id=item.Id})
                                        <div href="#" class="btn btn-warning btn-circle btn-sm">
                                            <i class="fas fa-pen"></i>
                                        </div>
                                        @Html.ActionLink("Edit", "Edit", new {  id=item.Id})
                                        <div href="#" class="btn btn-danger btn-circle btn-sm">
                                            <i class="fas fa-trash"></i>
                                        </div>
                                        @Html.ActionLink("Delete", "Delete", new {  id=item.Id}, new { onclick = "return confirm('Are sure wants to delete?');" })
                                    </td>
            
                                </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
       
    </body>
</html>